<a href="https://colab.research.google.com/github/Ahmed15497/Advanced-Machine-Learning-Specialization/blob/master/mininet_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [40]:
import pandas as pd

df1 = pd.read_csv('/content/drive/MyDrive/freelancing/mininet/dataset/normal/final_internet_browsing.csv')
df2 = pd.read_csv('/content/drive/MyDrive/freelancing/mininet/dataset/normal/final_iperf.csv')
#df3 = pd.read_csv('/content/drive/MyDrive/freelancing/mininet/dataset/normal/internet-browsing2.csv')

In [41]:
df_merged   = pd.concat((df1, df2), ignore_index=True)
df_merged.insert(0, 'class', 0)
df_merged.to_csv( "/content/drive/MyDrive/freelancing/mininet/dataset/normal/final_normal.csv", index=False)

In [42]:
df1 = pd.read_csv('/content/drive/MyDrive/freelancing/mininet/dataset/normal/final_normal.csv')

In [43]:
df1

       class    src_ip  ... subflow_fwd_byts  subflow_bwd_byts
0          0  10.0.0.1  ...              170               214
1          0  10.0.0.1  ...              840              3054
2          0  10.0.0.1  ...              170               214
3          0  10.0.0.1  ...              949              6185
4          0  10.0.0.5  ...               87                 0
...      ...       ...  ...              ...               ...
16423      0  10.0.0.4  ...          9307872                 0
16424      0  10.0.0.2  ...        655049222            306344
16425      0  10.0.0.4  ...          3919104                 0
16426      0  10.0.0.1  ...           633528                 0
16427      0  10.0.0.3  ...        441850926            131124

[16428 rows x 83 columns]

In [52]:
import os, glob
import pandas as pd

path = "."

all_files = glob.glob(os.path.join(path, "*.csv"))
df_from_each_file = (pd.read_csv(f, sep=',') for f in all_files)
df_merged   = pd.concat(df_from_each_file, ignore_index=True)
df_merged.insert(0, 'class', 1)
df_merged.to_csv( "final_attack.csv", index=False)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DtypeWarning: Columns (0,1,5) have mixed types.Specify dtype option on import or set low_memory=False.